### ISSUE TITLE
Dialog height in safari

### ISSUE THREAD

**Issue by andredewaard** [argyleink/gui-challenges#201]
Dialog height in safari defaults to 'fit-content'. Fixed it with an hardcode 
```css
dialog {
  height: min-content;
}
```
Any known complications by doing this?

PS: really nice dialog tutorial btw

**Comment by argyleink** [comment]
oh! i seem to be able to consistently fix it with

```css
dialog {
  max-block-size: max-content;
  height: auto;
}
```

`height: min-content;` showed an error in the styles pane that it wasn't valid
