### ISSUE TITLE
Game menu

### ISSUE THREAD

**Issue by vasilich6107** [argyleink/gui-challenges#202]
We can also add something like

```css
.menu-3d .button-set-3d > li:is(:hover, :focus-visible):not(:active) {
  --menu-3d-distance: 3vmax;
}

.menu-3d .button-set-3d > li button:not(:active) {
  transition-timing-function: var(--menu-3d-bounce-ease);
  transition-duration: 0.4s;
}
```

to reduce glitch when button popus up and automatically loses focus)
When we move the mouse relatively slowly.

Mostly relates to top most and bottom most buttons)
